### ISSUE TITLE
clarity on the panselset divs

### ISSUE THREAD

**Issue by adamkemberling** [j-jayes/jjayes_distill#1]
Hi, thank you for taking the time to share this post, very helpful and to the point. My only comment would be that it is not immediately clear that you type the:

`:::::{.panselset}
:::::`

As text, and that you need to include either a for loop or an apply function within that section (since you have {tidyverse} loaded dplyr::walk() works well). And also that they need to be within an r chunk with `results = "asis"`. I was able to quickly check it here, but that would take the post to that sweet spot of simple and complete.

Again, thanks for sharing! Lines are referenced below:

https://github.com/j-jayes/jjayes_distill/blob/145f634976ad08fe00f1fb00bd680b23fd6d99b7/_posts/2022-03-04-programmatically-generate-tabs-in-rmarkdown/programmatically-generate-tabs-in-rmarkdown.Rmd#L81-L95

**Comment by j-jayes** [comment]
Hi Adam - thanks for taking the time to comment such that I can improve the post. I appreciate it!

I shall be sure to update it soon reflecting the fenced div structure and the chunk options - in the meantime, I have a [short presentation](https://j-jayes.github.io/Monday-Munch/#8) with more concrete explanations, and a [link](https://stackoverflow.com/questions/63397427/programmatically-create-tab-and-plot-in-markdown) to a useful StackOverflow post.

**Comment by adamkemberling** [comment]
Not a problem - this is such a game changer for me, I am very often generating  the same plot for multiple species/areas/factors so this cleans up my markdown dramatically, I also wasn't aware that I could use the panelset in markdown either so it was a big find.

I did make one tweak to make it more generalizable to different plot functions which I found cut down my code just a bit more:
```
# Function to generate panels using a key word and a plot function
plot_panelset <- function(spec, plot_fun, ...) {
  
  # Open panel
  cat("::: {.panel}\n")

  # Create header for panel name
  cat("##", spec, "{.panel-name}\n")

  # # Text as a plot description
  # cat("Plot of", spec, "\n")

  # Make plot
  p <- plot_fun(spec, ...)
  print(p)

  # Add linebreak
  cat("\n")

  # Close panel
  cat(":::\n")
}
```
Then in practice I can pass different plot functions with any arguments they might need:

```
::::: {.panelset}

```{r, results="asis", fig.height=8}
# Loop through the key species:
walk(key_species, plot_panelset, plot_fun = saa_boxplot, var_choice = "length")

:::::
```
Again, really appreciate you sharing.

**Comment by j-jayes** [comment]
Fantastic - thank you! I like the idea of making the `plot_panelset` function even more flexible with different plot arguments. I've updated the post and linked your comment at the top. It was kind of you to take the time! Stay well 🙌
